
development:
  adapter: postgresql
  database: restful_api_rails_development

test:
  adapter: postgresql
  database: restful_api_rails_test

production:
  adapter: postgresql
  database: restful_api_rails_production
